apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: joyce-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: k8s.joyceheyue.fun
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: joyce-app
            port:
              number: 8080
